### ISSUE TITLE
Make sure MetaMask's upcoming breaking changes don't affect yearn

### ISSUE THREAD

**Issue by x48-crypto** [yearn/iearn-finance#167]
Need to review changes to `window.ethereum` (I think we are covered here) and `networkVersion`.

We need to be careful about potential regressions with `networkVersion` as a recent change caused reverse ENS resolution to fail.

**Comment by mehranhydary** [comment]
Seems like the repo is using @web3-react to check for what gets injected... so as long as those libraries can handle the updates that are coming to MetaMask the repo should be fine.

The changes for MetaMask 8.1 are summarized below for reference: 
1. For future updates... always use the chainChanged event to detect network changes. The networkChanged event is deprecated.
2. Currently, we need to ensure that the @web3-react library expects "networkChanged" to emit with **ONLY** decimal string values

Since the repo also only works for mainnet right now - I agree with @x48-crypto that we should be covered...

**Comment by x48-crypto** [comment]
This is resolved
